import type {Metadata} from "next";
import {Inter} from "next/font/google";

// styles
import "./globals.css";
import "@/assets/styles/style.scss";

// components
import Header from "@/components/context/Header.jsx";
import Footer from "@/components/context/Footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata =
  {
    title: "Create Next App",
    description:
      "Generated by create next app",
  };
// frontend test commit
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className
        }
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
