services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      # 현재 로컬 postgres와 docker image와 맵핑
      - ./postgres-data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: postgres
